### ISSUE TITLE
ONNX issue with multiple outputs (C++)

### ISSUE THREAD

**Issue by suman-v** [microsoft/onnxruntime-inference-examples#139]
I am able to run this ONNX model in python but not able to decode the output in C++. Please find image below and let me know if there are method to decode the output when Output dimension in unknown. 
**Netron visualization**
![Capture](https://user-images.githubusercontent.com/43817111/188087595-a330b6c7-6a80-4546-bf98-1e36572b9bcc.PNG)
**Python Output**

1. Array 1 is boundary boxes
2. Array 2 is class labels
3. Array 3 is confidence

![image](https://user-images.githubusercontent.com/43817111/188091003-da4186e0-dafa-4479-9a31-cff23890876f.png)
I can add model if required but as of now model size is more than 500mb.

**Comment by edgchen1** [comment]
To get the shape from a tensor, you can call:
- [Value::GetTensorTypeAndShapeInfo](https://onnxruntime.ai/docs/api/c/struct_ort_1_1_value.html#a3fe6e43ecc5679d3e547183f36248c9d) to get the TensorTypeAndShapeInfo. Value should be a Tensor.
- [TensorTypeAndShapeInfo::GetDimensionsCount](https://onnxruntime.ai/docs/api/c/struct_ort_1_1_tensor_type_and_shape_info.html#a6ebc72c10f10b400bbf53eee4b26e368) to get the number of dimensions.
- [TensorTypeAndShapeInfo::GetDimensions](https://onnxruntime.ai/docs/api/c/struct_ort_1_1_tensor_type_and_shape_info.html#a42370b300519e3af7d0b34f91778bb44) to get the dimensions.
