### ISSUE TITLE
Looking for java examples

### ISSUE THREAD

**Issue by jhgan00** [microsoft/onnxruntime-inference-examples#141]
Is there any inference example written in Java?

Also, I wonder if I can contribute to this repo if I write some java examples.

Thanks.

**Comment by 587687525** [comment]
Me too

**Comment by yuslepukhin** [comment]
I don't we think we have any Java samples. If I was writing Java code would simply look at `java/src/tests` and use it. Contributions are always welcom. 

Cc: @Craigacp

**Comment by Craigacp** [comment]
There's this example - https://github.com/microsoft/onnxruntime/blob/main/java/src/test/java/sample/ScoreMNIST.java in addition to the test code in the java folder. You can see an alternative use in Tribuo's ORT wrapper - https://github.com/oracle/tribuo/blob/main/Interop/ONNX/src/main/java/org/tribuo/interop/onnx/ONNXExternalModel.java, the code in that package shows a few different ways of preparing inputs and parsing outputs from ORT. There's an example of using it with a BERT style model here - https://github.com/oracle/tribuo/blob/main/Interop/ONNX/src/main/java/org/tribuo/interop/onnx/extractors/BERTFeatureExtractor.java.

I've not had time to write samples for the Java code beyond the tests, so more examples would be welcome.

**Comment by jhgan00** [comment]
Thanks a lot !!
