### ISSUE TITLE
Is there any example for linux c++ API?

### ISSUE THREAD

**Issue by zyandtom** [microsoft/onnxruntime-inference-examples#15]
Currently I try to inference the onnx model in c++ with ubuntu18, but I did not find any tutorial.

**Comment by DefTruth** [comment]
> Currently I try to inference the onnx model in c++ with ubuntu18, but I did not find any tutorial.

Coincidentally, I have add some c++ demo in my [repo](https://github.com/DefTruth/lite.ai), such as YoloV5.

**Comment by zyandtom** [comment]
> > Currently I try to inference the onnx model in c++ with ubuntu18, but I did not find any tutorial.
> 
> Coincidentally, I have add some c++ demo in my [repo](https://github.com/DefTruth/lite.ai), such as YoloV5.

Thank you !
