### ISSUE TITLE
What are these numbers [123.68,116.78,103.94] in resnet50_data_reader.py ?

### ISSUE THREAD

**Issue by saurabh260120** [microsoft/onnxruntime-inference-examples#262]
In _quantization/image_classification/cpu/resnet50_data_reader.py_
 
what are these numbers **[123.68,116.78,103.94]**  in line number 29

input_data = numpy.float32(pillow_img) - numpy.array(
            **[123.68, 116.78, 103.94]**, dtype=numpy.float32
)

**Comment by jywu-msft** [comment]
i think it's for normalizing the RGB channels as part of standardizing inputs for ResNet models. it's mentioned in papers such as https://arxiv.org/pdf/1812.01187.pdf
