### ISSUE TITLE
Error code - ORT_FAIL

### ISSUE THREAD

**Issue by marouanetalaa** [microsoft/onnxruntime-inference-examples#302]
Error: Error code - ORT_FAIL - message: subgraph_whisper_decoder.cc:62 Validate number of inputs expected to be kFirstPastInputIndex + 4 * layers, got:18

Mobile example on android not running correctely since last week

**Comment by hariharans29** [comment]
CC: @kunal-vaishnavi

**Comment by skottmckay** [comment]
What onnxruntime version are you using? I believe the sample was updated last week to work with version 1.16. 

https://github.com/microsoft/onnxruntime-inference-examples/pull/300

**Comment by huyletran** [comment]
Error: Error code - ORT_FAIL - message: subgraph_whisper_encoder.cc:43 Validate expect 2 inputs, got:3
Mobile example on android not running

**Comment by edgchen1** [comment]
The CI build for this example is passing with the latest version of the code in main. Please try using the latest.

**Comment by huyletran** [comment]
I have used onnxruntime latest version

**Comment by natke** [comment]
Can you please dump your environment here ie pip list. Thank you

**Comment by huyletran** [comment]
I build example from https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/speech_recognition/android, in gradle onnxruntime latest version but i run got error Error: Error code - ORT_FAIL - message: subgraph_whisper_encoder.cc:43 Validate expect 2 inputs, got:3

**Comment by edgchen1** [comment]
Does it still fail at this commit?
https://github.com/microsoft/onnxruntime-inference-examples/commit/980def0d59147b6117523cc756c89a10079ff8e4

**Comment by huyletran** [comment]
Thank you.980def0 works now.
