### ISSUE TITLE
Example references QNN version and files not available

### ISSUE THREAD

**Issue by hschumanncvx** [microsoft/onnxruntime-inference-examples#325]
The C++ example for QNN EP [here](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/QNN_EP) references QNN SDK 2.15.1.230926 yet 2.15.0.230926 is the latest available version from the [Qualcomm Package Manager](https://qpm.qualcomm.com/#/main/tools/details/qualcomm_neural_processing_sdk). Folders/files referenced in the example such as C:\Qualcomm\AIStack\QNN\2.15.1.230926\lib\hexagon-v73 are not available in v2.15.0.230926.

**Comment by ivberg** [comment]
@hschumanncvx it seems like it's available to me (see below).

However, please note that I tested both this QNN version you mention and latest 2.15.3.231006. They both have issues at least with the example - https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/QNN_EP/mobilenetv2_classification

We have tested successfully on SQ3 (Surface Pro 9 5G or Windows Dev Kit 2023) on QNN 2.14.1.230828. This info on last known good working QNN version has been added to inf example readme via PR #324 
```
>dir C:\Qualcomm\AIStack\QNN\2.15.1.230926\lib\hexagon-v73\unsigned\libQnnHtpV73Skel.so
 Volume in drive C is Local Disk
 Volume Serial Number is 5836-7239

 Directory of C:\Qualcomm\AIStack\QNN\2.15.1.230926\lib\hexagon-v73\unsigned

10/06/2023  01:56 PM         6,737,072 libQnnHtpV73Skel.so
```

**Comment by HectorSVC** [comment]
2.15.0 is the official release. 2.15.1 is preview release, not all customers have the access to it. We need to skip the V73 if it's not existed. Sorry to the confusion.

**Comment by HectorSVC** [comment]
I added some notes to avoid confusion: https://github.com/microsoft/onnxruntime-inference-examples/pull/326

**Comment by Nick-infinity** [comment]
Hello @ivberg , What are the chances of getting a LLM work with QNN backend using onnx mobile device deployement. I am not sure if there will be memory limitations. Can you see any obvious limitations in running LLMs using the same example mentioned in latest mobileclassification model.

**Comment by HectorSVC** [comment]
@hschumanncvx, Can we close this issue if no further quations?

**Comment by hschumanncvx** [comment]
@HectorSVC yes this particular issue you can close, but I did raise another issue here https://github.com/microsoft/onnxruntime-inference-examples/issues/344. Thanks
