### ISSUE TITLE
QNN Execution provider -  QNN context binary generated fail

### ISSUE THREAD

**Issue by Francis235** [microsoft/onnxruntime-inference-examples#369]
I follow the instructions: https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html, compile and build the onnxruntime lib used on Qualcomm 8155 chip, I can run successfully on 8155 with QNN backend.
![image](https://github.com/microsoft/onnxruntime-inference-examples/assets/51819537/3a33ce63-4dc1-4d9c-a02b-d97e7bca7070)
I want to generate QNN context binary file to improve loading cost, and I config my code according to the instruction, but I don't find the  QNN context binary generated. The following is my part config code:

if (strcmp(argv[3], CPUBACKEDN) == 0) {
      backend = "/lib/libQnnCpu.so";
      std::cout << "The backend you use is CPU. " << std::endl; 
    } else if (strcmp(argv[3], HTPBACKEDN) == 0)
    {
      backend = "/lib/libQnnHtp.so";
      std::cout << "The backend you use is HTP. " << std::endl; 
    } else {
      std::cout << "This sample only support option cpu, htp, qnn." << std::endl;
    }

auto providers = Ort::GetAvailableProviders();
	for (auto provider : providers)
		std::cout << provider << std::endl;   

    g_ort->AddSessionConfigEntry(session_options, kOrtSessionOptionEpContextEnable, "1");
    g_ort->AddSessionConfigEntry(session_options, kOrtSessionOptionEpContextEmbedMode, "0");
    g_ort->AddSessionConfigEntry(session_options, kOrtSessionOptionEpContextFilePath, "/qnn_ctx.onnx");

    std::vector<const char*> options_keys = {"backend_path"};
    std::vector<const char*> options_values = {backend.c_str()};

    g_ort->SessionOptionsAppendExecutionProvider(session_options, "QNN", options_keys.data(), options_values.data(), options_keys.size());
    
    Any suggestions will be help, thank you.

**Comment by HectorSVC** [comment]
Did you get any error message?

g_ort->AddSessionConfigEntry(session_options, kOrtSessionOptionEpContextFilePath, "/qnn_ctx.onnx");
I'm not sure if /qnn_ctx.onnx is a valid file path.

**Comment by Francis235** [comment]
> Did you get any error message?
> 
> g_ort->AddSessionConfigEntry(session_options, kOrtSessionOptionEpContextFilePath, "/qnn_ctx.onnx"); I'm not sure if /qnn_ctx.onnx is a valid file path.

no error message occurs.  I ignore part file path, the full file path like "    g_ort->AddSessionConfigEntry(session_options, kOrtSessionOptionEpContextFilePath, "/data/users/workspace/test_8155_deploy/test_model/qnn_ctx.onnx");
"

**Comment by HectorSVC** [comment]
You can change the log level to verbose to get more logs:
option 1: https://github.com/microsoft/onnxruntime-inference-examples/blob/8aa043ceb48be17baf328c2b71b58a1eb9bc35f1/c_cxx/QNN_EP/mobilenetv2_classification/main.cpp#L73-L74
option 2: set through session options.

Maybe not all nodes partitioned to QNN EP, it's a limitation so far that we require all nodes running on QNN EP.
You can also share your model with us to make it easier.

**Comment by Francis235** [comment]
Thanks for your reply. Sorry for the late reply, I'm busy with other things recently. I just tried it， and after changing the log level to verbose,  I didn't get more logs. By the way, have you tested the QNN EP on Qualcomm SA8155 chip?

> You can change the log level to verbose to get more logs: option 1:
> 
> https://github.com/microsoft/onnxruntime-inference-examples/blob/8aa043ceb48be17baf328c2b71b58a1eb9bc35f1/c_cxx/QNN_EP/mobilenetv2_classification/main.cpp#L73-L74
> 
> 
> option 2: set through session options.
> Maybe not all nodes partitioned to QNN EP, it's a limitation so far that we require all nodes running on QNN EP. You can also share your model with us to make it easier.

**Comment by Francis235** [comment]
Hi, I have learned that the Qualcomm SA8155 seems a V66 chipset. QNN-HTP doesn't support V66.
We need QNN-DSP to support V66. I noticed that the documentation in the onnxruntime EP part only mentions support for QNN-HTP devices. Does onnxruntime EP support QNN-DSP, which is used in SA8155. Do you have any comments on this?

> You can change the log level to verbose to get more logs: option 1:
> 
> https://github.com/microsoft/onnxruntime-inference-examples/blob/8aa043ceb48be17baf328c2b71b58a1eb9bc35f1/c_cxx/QNN_EP/mobilenetv2_classification/main.cpp#L73-L74
> 
> 
> option 2: set through session options.
> Maybe not all nodes partitioned to QNN EP, it's a limitation so far that we require all nodes running on QNN EP. You can also share your model with us to make it easier.

**Comment by Francis235** [comment]
I will test the mobilenetv2 model provided in examples later, and I will synchronize my test results in time. I suspect that onnxruntime EP does not support the SA8155 chip (QNN-DSP).

**Comment by HectorSVC** [comment]
Ort QNN EP supports what QNN SDK supports. You can try set the backend_path to the libQnnDsp.so.

**Comment by HectorSVC** [comment]
@Francis235 Can we close this issue if no more questions?

**Comment by HectorSVC** [comment]
@Francis235 I'm going to close this one if no more questions.
