### ISSUE TITLE
error "QNN execution provider is not supported in this build" when testing ONNX QNN EP

### ISSUE THREAD

**Issue by shawnyxf** [microsoft/onnxruntime-inference-examples#397]
Recently, i'm trying to use QNN EP in ONNX to make my model run faster on Android platform:

So i compiled the onnx + qnn android dynamic library according to https://onnxruntime.ai/docs/build/eps.html#qnn

ONNX VERSION: 1.16.3
QNN SDK: 2.20.0.240223

After finishing the compile, i add some related code in my project (i wanna test on cpu backend)：

	std::string backend = "QnnCpu.so";
	std::vector<const char*> options_keys = {"backend_path"};
	std::vector<const char*> options_values = {backend.c_str()};

	ORT_ABORT_ON_ERROR(g_ort->SessionOptionsAppendExecutionProvider(st->session_options, "QNN", options_keys.data(), options_values.data(), options_keys.size()));

then i run my project on android, i get the error "QNN execution provider is not supported in this build".

Can anyone help me solve my problem?

**Comment by Francis235** [comment]
Hello, I want to know what qualcomm soc platform you use?

**Comment by shawnyxf** [comment]
> Hello, I want to know what qualcomm soc platform you use?

Hi, thanks for replying, i use qualcomm 8295

**Comment by shawnyxf** [comment]
> Recently, i'm trying to use QNN EP in ONNX to make my model run faster on Android platform:
> 
> So i compiled the onnx + qnn android dynamic library according to https://onnxruntime.ai/docs/build/eps.html#qnn
> 
> ONNX VERSION: 1.16.3 QNN SDK: 2.20.0.240223
> 
> After finishing the compile, i add some related code in my project (i wanna test on cpu backend)：
> 
> ```
> std::string backend = "QnnCpu.so";
> std::vector<const char*> options_keys = {"backend_path"};
> std::vector<const char*> options_values = {backend.c_str()};
> 
> ORT_ABORT_ON_ERROR(g_ort->SessionOptionsAppendExecutionProvider(st->session_options, "QNN", options_keys.data(), options_values.data(), options_keys.size()));
> ```
> 
> then i run my project on android, i get the error "QNN execution provider is not supported in this build".
> 
> Can anyone help me solve my problem?

Just change the QNN sdk version to 2.18.0.240101, it works
