### ISSUE TITLE
how to deploy my own onnx yolov8 model?

### ISSUE THREAD

**Issue by Christian-lyc** [microsoft/onnxruntime-inference-examples#469]
Hi, I want to ask what is the difference between the example onnx model, yolov8n_with_pre_post_processing.onnx and the ultralytics onnx model? I can't load my ultralytics model there. Could anyone help me? Thank you so much

**Comment by adrianlizarraga** [comment]
Hi @Christian-lyc,

The yolov8n_with_pre_post_processing.onnx model adds extra preprocessing and postprocessing nodes to the actual model obtained from ultralytics.

In essence, the yolov8n_with_pre_post_processing.onnx model looks like:
`input -> preprocess_nodes -> yolov8n_nodes -> posprocess_nodes -> output`

We can load both models in Netron to inspect the differences (yolov8n_with_pre_post_processing.onnx is on the left, ultralytics on the right):
![Image](https://github.com/user-attachments/assets/16c5aaf6-50b4-4f83-b991-e55cb9a9706c)

You can see that the yolov8n_with_pre_post_processing.onnx models adds extra nodes to the beginning (and end) of the model. Also, the yolov8n_with_pre_post_processing.onnx model takes in `uint8` input, whereas the original ultralytics model takes in `float32` input.

The [documentation ](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/object_detection/android#overview)for the example explains:
> The model used here is from source: [Yolov8 in extensions](https://github.com/microsoft/onnxruntime-extensions/blob/64f20828ce0291394886e277c23529cd1d11320d/tutorials/yolo_e2e.py#L37) and with pre/post processing support.
This model (Yolov8n) can be fed with image bytes directly and outputs the detected objects with bounding boxes.

The [link above](https://github.com/microsoft/onnxruntime-extensions/blob/64f20828ce0291394886e277c23529cd1d11320d/tutorials/yolo_e2e.py#L37) shows how the yolov8n_with_pre_post_processing.onnx is created from the original ultralytics model. Here's a snippet:
```python
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
import numpy

from pathlib import Path
import onnxruntime_extensions


def get_yolov8_model(onnx_model_name: str):
    # install yolov8
    from pip._internal import main as pipmain
    try:
        import ultralytics
    except ImportError:
        pipmain(['install', 'ultralytics'])
        import ultralytics
    pt_model = Path("yolov8n.pt")
    model = ultralytics.YOLO(str(pt_model))  # load a pretrained model
    success = model.export(format="onnx")  # export the model to ONNX format
    assert success, "Failed to export yolov8n.pt to onnx"
    import shutil
    shutil.move(pt_model.with_suffix('.onnx'), onnx_model_name)


def add_pre_post_processing_to_yolo(input_model_file: Path, output_model_file: Path):
    """Construct the pipeline for an end2end model with pre and post processing. 
    The final model can take raw image binary as inputs and output the result in raw image file.

    Args:
        input_model_file (Path): The onnx yolo model.
        output_model_file (Path): where to save the final onnx model.
    """
    if not Path(input_model_file).is_file():
        get_yolov8_model(input_model_file)

    from onnxruntime_extensions.tools import add_pre_post_processing_to_model as add_ppp
    add_ppp.yolo_detection(input_model_file, output_model_file, "jpg", onnx_opset=18)
```
