### ISSUE TITLE
why relu is missing after quantize_static?

### ISSUE THREAD

**Issue by twmht** [microsoft/onnxruntime-inference-examples#50]
Hi,

I found out that relu is missing after `quantize_static`.

![image](https://user-images.githubusercontent.com/1567200/139226491-0ac3ec6b-212b-4403-9af5-5a935ecd43fc.png)

this graph is the beginning part of resnet50,  it has `relu` after `add` operator. why is missing? did you fuse `add` and `relu`  together?

**Comment by yufenglee** [comment]
yes, it is fused into the re-quant logic.
