### ISSUE TITLE
Oudated code in model-explorer in c_cxx examples

### ISSUE THREAD

**Issue by yummyKnight** [microsoft/onnxruntime-inference-examples#69]
Currently code presented in [model-explorer](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/model-explorer/model-explorer.cpp) using outdated API. For example Experimental namespace no longer exists. session object don't have member GetInputShapes, etc.

**Comment by yummyKnight** [comment]
Example of using current API (1.10.0) - https://github.com/ilpropheta/onnxruntime-demo/blob/master/OnnxRuntimeDemoGPU/main.cpp

**Comment by ahammers** [comment]
Same problem here. This example seemed like a perfect starting point but it is using an old(?) experimental interface and the current interface seems to be less intuitive and definetly needs an example.

**Comment by fnobis** [comment]
thanks @yummyKnight for the link, however the api also already seems outdated. E.g. the `#include "cuda_provider_factory.h"` file is no longer present in the release packages. There are additional errors seeming  to be originating from the change of api, if you remove this include. 

Is there any working simple example for the current api? Not using tensorrt or anything, just a plain example would be very helpful.

**Comment by wangsen1312** [comment]
https://github.com/leimao/ONNX-Runtime-Inference  I found this repo is useful and up-to-date
