### ISSUE TITLE
Problem onnxruntime node - windows server 2019

### ISSUE THREAD

**Issue by mbravo1** [microsoft/onnxruntime-inference-examples#75]
I try to run the quick-start_onnxruntime-node but in Windows Server 2019 Standard it does not work, it shows the following error, in windows 10 there is no problem. According to the documentation it works for windows server 2019.

Could you help me what is happening?

![image](https://user-images.githubusercontent.com/2030001/154185443-c4391cc5-573f-411c-ab63-56a211bec16e.png)

Thank you very much!

**Comment by snnn** [comment]
We need more information to help you.

Below instructions are for python. But it works the same for nodejs.

To identify the problem:
1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2.  Find the gflags.exe in the windbg install folder and start it, 

3. Select the image file tab
![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)

4. Type node.exe then press the "tab" key, check "Show loader snaps" box . The image below is for python.

![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)

5.  Put your python commands into a script file, named "test.py" (here I mean: put your js code in a js file)
```
import torch
import onnxruntime
```

6.  Start windbg, run python.exe with arguments of "test.py"
![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)

7. in the command windows, type "g", then press the enter key
![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)

7. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
e.g.
 "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135


Please post the log here if you can't find the problematic DLL by yourself.

**Comment by mbravo1** [comment]
Hello @snnn. 

I really appreciate your support.

I did the procedure that you indicated to me, the dll is the following:

1de4:1574 @ 185018671 - LdrpProcessWork - ERROR: Unable to load DLL: "VCRUNTIME140_1.dll", Parent Module: "\\?\C:\Users\Administrator\Downloads\ex\node_modules\onnxruntime-node\bin\napi-v3\win32\x64\onnxruntime_binding.node", Status: 0xc0000135


Thank you very much!

**Comment by snnn** [comment]
See: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

Please install the latest vc redist.

VCRUNTIME140_1.dll is for VS 2019. You only have the dlls for VS 2017.

**Comment by mbravo1** [comment]
Hello @snnn.

I really appreciate your support. 

The problem is solved by updating to 2019

Thank you very much!
