### ISSUE TITLE
Failing to get inference result in C++

### ISSUE THREAD

**Issue by JNSFilipe** [microsoft/onnxruntime-inference-examples#78]
I have an ONNX model that I trained using XGBoost and onnxmltools, and sucessfully tested in python using onnxruntime. I am now trying to load the model form C++, but I am unable to get viable inferences back. For this pouropose, I build a facilitator class, inspired by this [example](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/MNIST/MNIST.cpp) and this [example](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/imagenet/main.cc). The calss looks like this:

```cpp
#include <onnxruntime_cxx_api.h>

class Predictor{
  public:
    Ort::Session session{nullptr};
    Ort::MemoryInfo memory_info{nullptr};
    char* input_name = nullptr;
    char* output_name = nullptr;
    std::vector<int64_t> *dims;

    Predictor(std::string path) {
      Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "fast-inference");
      Ort::SessionOptions sessionOptions;
      sessionOptions.SetIntraOpNumThreads(1);
      sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

      this->session = Ort::Session(env, path.c_str(), sessionOptions);
      this->memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

      Ort::AllocatorWithDefaultOptions ort_alloc;
      input_name = this->session.GetInputName(0, ort_alloc);
      output_name = this->session.GetOutputName(1, ort_alloc); // 0 returns the labels, 1 returns the probabilities

      Ort::TypeInfo info = this->session.GetInputTypeInfo(0);
      auto tensor_info = info.GetTensorTypeAndShapeInfo();
      size_t dim_count = tensor_info.GetDimensionsCount();
      dims = new std::vector<int64_t>(dim_count);
      tensor_info.GetDimensions((*dims).data(), (*dims).size());
    };

    float* get_prediction(std::vector<float> f){
      const char* i[] = {this->input_name};
      const char* o[] = {this->output_name};

      (*this->dims)[0] = 0; // Apperently, dims are reported as (-1, 6), which generates an error. This changes the -1 to 0.

      auto input_tensor = Ort::Value::CreateTensor<float>(this->memory_info, f.data(), f.size(), (*this->dims).data(), (*this->dims).size());
      Ort::Value output_tensor{nullptr};

      // Ort::Value output_tensor{nullptr};
      // std::vector<Value> p this->session.Run(Ort::RunOptions{nullptr}, i, &input_tensor, 1, o, &output_tensor, 1);
      auto h = this->session.Run(Ort::RunOptions{nullptr}, i, &input_tensor, 1, o, 1);
      float* probs = h[0].GetTensorMutableData<float>();
      
      retrun probs; // <- Problem is here: probs is 0x00 and appears to hold no value
    };
};

void main(){
  Predictor pred("./model.onnx");
  std::vector<float> features{0.0268593, 0.20130636, 0.18040432, 0.11453316, 0.17075175, 0.0};
  auto r = pred.get_prediction(features);
}
```

However, the vector where the probabilities should be stored appears to be empty. Any clue on what the problem may be?

**Comment by snnn** [comment]
Please check the data types. Sometimes the models do not use tensors as input/output. 
Please use https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md to print out the model's input/output information and post it there.

**Comment by JNSFilipe** [comment]
In the first place, thank you very much for your answer. Regarding your seggestion, I inspected the page you mentionened, but failed to see a way to print the input/output data types. However, after some googling, I came up with the following:

```python
import onnx
onnx_model = onnx.load('./model.onnx')
for _input in onnx_model.graph.input:
    print(_input)
```
Resulting in:
```
name: "float_input"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
      }
      dim {
        dim_value: 6
      }
    }
  }
}
```
And:
```python
for _output in onnx_model.graph.output:
    print(_output)
```
Which yields:
```
name: "label"
type {
  tensor_type {
    elem_type: 7
    shape {
      dim {
      }
    }
  }
}

name: "probabilities"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
      }
      dim {
        dim_value: 2
      }
    }
  }
}
```
Thus, as long as I can understand, both the input and the outputs are tensors (`tensor_type`), right?

**Comment by snnn** [comment]
Yes, you are right. But you have two outputs, and you only defined one output_tensor. You need two output tensors.

**Comment by snnn** [comment]
The input parameters of the run methods are:

1. run_options If nullptr, will use a default ::OrtRunOptions
2. input_names Array of null terminated UTF8 encoded strings of the input names
3. inputs Array of ::OrtValue%s of the input values
4. input_len Number of elements in the input_names and inputs arrays
5. output_names Array of null terminated UTF8 encoded strings of the output names
6. output_names_len Number of elements in the output_names and outputs array

**Comment by JNSFilipe** [comment]
According with what you said, I updated my class to account for mutiple outputs (I was convinced that you could chose just one output by providing only one name to the Run method). Thus, my code is now the following:

```cpp
#include <onnxruntime_cxx_api.h>

class Predictor{
  public:
    Ort::Session session{nullptr};
    Ort::MemoryInfo memory_info{nullptr};
    char *input_name = nullptr;
    std::vector<char*> output_names = {};
    int output_count;
    std::vector<int64_t> *dims;

    Predictor(std::string path) {
      Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "fast-inference");
      Ort::SessionOptions sessionOptions;
      sessionOptions.SetIntraOpNumThreads(1);
      sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

      this->session = Ort::Session(env, path.c_str(), sessionOptions);
      this->memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

      Ort::AllocatorWithDefaultOptions ort_alloc;
      input_name = this->session.GetInputName(0, ort_alloc);
      output_count = this->session.GetOutputCount();
      for(int i=0; i<output_count; i++)
        output_names.push_back(this->session.GetOutputName(i, ort_alloc));

      Ort::TypeInfo info = this->session.GetInputTypeInfo(0);
      auto tensor_info = info.GetTensorTypeAndShapeInfo();
      size_t dim_count = tensor_info.GetDimensionsCount();
      dims = new std::vector<int64_t>(dim_count);
      tensor_info.GetDimensions((*dims).data(), (*dims).size());
    };

    float* get_prediction(std::vector<float> f){
      const char* i[] = {this->input_name};

      (*this->dims)[0] = 0; // Apperently, dims are reported as (-1, 6), which generates an error. This changes the -1 to 0.

      auto input_tensor = Ort::Value::CreateTensor<float>(this->memory_info, f.data(), f.size(), (*this->dims).data(), (*this->dims).size());

      auto h = this->session.Run(Ort::RunOptions{nullptr}, i, &input_tensor, 1, this->output_names.data(), this->output_count);
      float* probs = h[0].GetTensorMutableData<float>();
      
      retrun probs; // <- Problem is here: probs is 0x00 and appears to hold no value
    };
};

void main(){
  Predictor pred("./model.onnx");
  std::vector<float> features{0.0268593, 0.20130636, 0.18040432, 0.11453316, 0.17075175, 0.0};
  auto r = pred.get_prediction(features);
}
```

Unfortunately, the problem presists and vector `probs` still points to `0x00`.

**Comment by snnn** [comment]
Have you printed output_names out? How do you know h[0] is "label" or "probs"?

**Comment by JNSFilipe** [comment]
Yes, I have and I tried the code with both h[0] and h[1], but the probs array is always empty. Just for the record, h[0] is the "label" and h[1] is the "probabilities".

**Comment by snnn** [comment]
probs is 0x00 or *probs is 0x00?

**Comment by JNSFilipe** [comment]
I am sorry, sould have been more precise in my language. It is *probs that is 0x00

**Comment by snnn** [comment]
```C++
      (*this->dims)[0] = 0; // Apperently, dims are reported as (-1, 6), which generates an error. This changes the -1 to 0.
```
-1 means unknown.  0 means empty. If your input is empty, output will be empty too.
So, please put a real non-negative value there, like: 1.  The values of dims should match the size of your f vector. I mean, if dims is [0,10], then the number of elements is 0*10=0, the f can be empty(or not). If dims is [1,10], then f.size() should be at least 10. 

Also, you can print out the shapes of h[0] and h[1] to verify.

**Comment by JNSFilipe** [comment]
Ok, that was the issue, thank you very much. Just a side note, it would be helpful if a higher leve interface wold be provided. Something like the class I wrote would alllow for quickly checking if the model is working as intended.
