### ISSUE TITLE
cannot open file 'atls.lib'

### ISSUE THREAD

**Issue by blinnassime** [microsoft/onnxruntime-inference-examples#85]
Hello,

I am unable to compile the examples because I get the follwing message:
LINK : fatal error LNK1104: cannot open file 'atls.lib'

I use windows 10 with visual studio 2019. I have cmake installed and onnxruntime installed for x86. When using cmake, I used the flag -DONNXRUNTIME_ROOTDIR=c:\hrl\ort_install

Could you help ?

Thanks

**Comment by cloudhan** [comment]
`atls.lib` belongs to [Desktop development with C++ workload](https://docs.microsoft.com/en-us/cpp/mfc/mfc-and-atl?view=msvc-170). Could you please ensure you visual studio has the component installed.
![image](https://user-images.githubusercontent.com/1279292/156688928-5820f125-bd55-441a-853b-9fba6c19205c.png)

**Comment by blinnassime** [comment]
It worked, thanks

**Comment by TsunamiServices** [comment]
Thank you so much!
